version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10 
  groups:
    pip-dependency:
      applies-to: version-updates
      patterns:
      - "*"
